# Generated by Django 6.0.2 on 2026-05-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['event', 'date_assigned', 'duty_number'], 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='issuetype',
            options={'verbose_name_plural': 'Issue Types'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name'], 'verbose_name_plural': 'Staff'},
        ),
    ]
