# Generated by Django 6.0.2 on 2026-05-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_assignment_options_alter_issuetype_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'assigned')), fields=('event', 'duty_number'), name='unique_active_assignment_per_duty'),
        ),
    ]
