# Generated by Django 6.0.2 on 2026-05-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_assignment_reassigned_at_assignment_reassigned_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='role_for_event',
        ),
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role for this event', null=True, on_delete=django.db.models.deletion.PROTECT, to='staff.role'),
        ),
    ]
