# Generated by Django 6.0.2 on 2026-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_role_remove_assignment_role_for_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(default='temp', unique=True),
            preserve_default=False,
        ),
    ]
