# Generated by Django 6.0.2 on 2026-05-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_role_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(help_text='Role for this event', on_delete=django.db.models.deletion.PROTECT, to='staff.role'),
        ),
    ]
