# Generated by Django 6.0.2 on 2026-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_applicant_cover_letter_alter_applicant_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('dropped', 'Dropped')], default='assigned', max_length=20),
        ),
    ]
