# Generated by Django 6.0.2 on 2026-05-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +2348012345678', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Format: 2348012345678 no + or spaces', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
