# Generated by Django 6.0.2 on 2026-05-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_eventtemplate_alter_assignment_staff_event_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.event'),
        ),
    ]
