# Generated by Django 6.0.2 on 2026-05-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_recruitment_related_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplay',
            name='scenario',
            field=models.TextField(),
        ),
    ]
