# Generated by Django 6.0.2 on 2026-05-29 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_roleplay_scenario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RolePlayResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='What the staff member said/did')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('roleplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='staff.roleplay')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleplay_responses', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Role Play Response',
                'verbose_name_plural': 'Role Play Responses',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
