# Generated by Django 6.0.2 on 2026-06-06 15:40

import staff.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_staff_options_applicant_interview_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=staff.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='next_of_kin',
            field=staff.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=staff.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='whatsapp',
            field=staff.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
    ]
