# Generated by Django 6.0.6 on 2026-06-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_rename_name_event_title_remove_event_date_and_more'),
    ]

    operations = [
    ]
