# Generated by Django 6.0.6 on 2026-06-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_eventtemplaterole'),
        ('staff', '0019_auto_20260629_0555'),
    ]

    operations = [
    ]
