# Generated by Django 6.0.6 on 2026-06-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_merge_0002_eventtemplaterole_0019_auto_20260629_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.role'),
        ),
    ]
