# Generated by Django 6.0.6 on 2026-06-29 10:53

import staff.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=staff.fields.EncryptedTextField(default='TBD', max_length=355),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_phone',
            field=staff.fields.EncryptedCharField(default='000', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='next_of_kin',
            field=staff.fields.EncryptedCharField(default='TBD', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=staff.fields.EncryptedCharField(default='000', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='whatsapp',
            field=staff.fields.EncryptedCharField(default='111', max_length=255),
        ),
    ]
