# Generated by Django 6.0.6 on 2026-06-29 11:02

import staff.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_alter_staff_address_alter_staff_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=staff.fields.EncryptedTextField(max_length=355),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_phone',
            field=staff.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='next_of_kin',
            field=staff.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=staff.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='whatsapp',
            field=staff.fields.EncryptedCharField(max_length=255),
        ),
    ]
